spring:
  security:
    user:
      name: notification
      password: notification
  boot:
    admin:
      client:
        enabled: false
  cloud:
    kubernetes:
      config:
        enabled: false
      reload:
        monitoring-config-maps: false

  liquibase:
    enabled: true
    drop-first: true
    default-schema: notification
    liquibase-schema: notification

  datasource:
    url: jdbc:postgresql://major:5432/skillbox
    username: notification
    password: notification
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
        default_schema: notification
    open-in-view: false

  kafka:
    consumer:
      group-id: event.1
    bootstrap-servers: 82.202.214.42:9094

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration